# Test your FastAPI endpoints
###

PUT http://127.0.0.1:8000/vehicles/3ab02;0d168f4335f3c84882baef8889f324b7
Accept: application/json

{
"make": "ford",
"model": "fiesta",
"registration": "AB6427"
}

###

PUT http://127.0.0.1:8000/vehicles/3ab02
Accept: application/json

{
"make": "chevrolet",
"model": "corvette",
"registration": "DEN823"
}

###

PUT http://127.0.0.1:8000/apps/96b27
Accept: application/json

{
"date": "12/12/2025",
"vehicle_id": "0e794",
"mechanic_id": "eb577"
}

###

PUT http://127.0.0.1:8000/mechanics/58aa0;685b87f66c212734f235bcec49ad2b25
Accept: application/json

{
"name": "adam",
"surname": "sandler"
}

###

PUT http://127.0.0.1:8000/mechanics/58aa0;05b13d52abac8e1bfe94a97bd6d4cb00
Accept: application/json

{
"name": "joe",
"surname": "kowalsky"
}

###